<?php

/**
 * @file
 * Site settings sample data file.
 */

 use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function site_settings_sample_data_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the site_settings sample data module.
    case 'help.page.site_settings_sample_data':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides site settings entity sample data') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function site_settings_sample_data_theme($existing, $type, $theme, $path) {
  return [
    'test_site_settings_not_loaded' => [
      'variables' => [],
    ],
  ];
}
