# Site Setting routing definition
entity.site_setting_entity.canonical:
  route_name: entity.site_setting_entity.canonical
  base_route: entity.site_setting_entity.canonical
  title: 'View'

entity.site_setting_entity.edit_form:
  route_name: entity.site_setting_entity.edit_form
  base_route: entity.site_setting_entity.canonical
  title: Edit

entity.site_setting_entity.delete_form:
  route_name:  entity.site_setting_entity.delete_form
  base_route:  entity.site_setting_entity.canonical
  title: Delete
  weight: 10

site_settings.admin:
  title: Site Settings
  route_name: entity.site_setting_entity.collection
  base_route: system.admin_content