services:
  site_settings.loader:
    class: Drupal\site_settings\SiteSettingsLoader
    arguments: ['@entity_type.manager', '@language_manager']

  site_settings.replicator:
    class: Drupal\site_settings\SiteSettingsReplicator
    arguments: ['@entity_type.manager']

  site_settings.renderer:
    class: Drupal\site_settings\SiteSettingsRenderer
    arguments: ['@renderer', '@entity_type.manager']

  cache.site_settings:
    class: Drupal\Core\Cache\CacheBackendInterface
    tags:
      - { name: cache.bin }
    factory: cache_factory:get
    arguments: [site_settings]
