<?php

/**
 * @file
 * Nothing to see here. It's all about the Field/FieldFormatter.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smart_trim_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.smart_trim':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Smart Trim implements a new field formatter for text fields (text, text_long, and text_with_summary, if you want to get technical) that improves upon the "Summary or Trimmed" formatter.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_field_migration_field_formatter_info().
 */
function smart_trim_field_migration_field_formatter_info() {
  return [
    'text' => ['smart_trim_format' => 'smart_trim'],
    'text_long' => ['smart_trim_format' => 'smart_trim'],
    'text_with_summary' => ['smart_trim_format' => 'smart_trim'],
  ];
}
