redirect_after_login.settings:
  type: config_object
  mapping:
    login_redirection:
      type: sequence
      label: 'Roles redirection'
      sequence:
        type: string
        label: 'Redirection URL'
    exclude_urls:
      type: string
      label: 'Exclude URLs'