<?php

/**
 * @file
 * Logs file entity CUD commands in the admin_audit_trail module.
 */

use Drupal\file\Entity\File;

/**
 * Implements hook_admin_audit_trail_handlers().
 */
function admin_audit_trail_file_admin_audit_trail_handlers() {
  $handlers = [];
  // File event log handler.
  $handlers['file'] = [
    'title' => t('File'),
  ];

  return $handlers;
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function admin_audit_trail_file_insert(File $file) {
  $log = [
    'type' => 'file',
    'operation' => 'insert',
    'description' => $file->getFileUri(),
    'ref_numeric' => $file->id(),
    'ref_char' => $file->getFilename(),
  ];

  // Insert log.
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function admin_audit_trail_file_update(File $file) {
  $log = [
    'type' => 'file',
    'operation' => 'update',
    'description' => $file->getFileUri(),
    'ref_numeric' => $file->id(),
    'ref_char' => $file->getFilename(),
  ];

  // Insert log.
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function admin_audit_trail_file_delete(File $file) {
  $log = [
    'type' => 'file',
    'operation' => 'delete',
    'description' => $file->getFileUri(),
    'ref_numeric' => $file->id(),
    'ref_char' => $file->getFilename(),
  ];

  // Insert log.
  admin_audit_trail_insert($log);
}
