<?php

/**
 * @file
 * Logs menu CUD commands in the admin_audit_trail module.
 */

/**
 * Implements hook_admin_audit_trail_handlers().
 */
function admin_audit_trail_taxonomy_admin_audit_trail_handlers() {
  // Taxonomy event log handler.
  $handlers = [];
  $handlers['taxonomy'] = [
    'title' => t('Taxonomy'),
  ];
  return $handlers;
}

/**
 * Implements hook_taxonomy_vocabulary_insert().
 */
function admin_audit_trail_taxonomy_taxonomy_vocabulary_insert($vocabulary) {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'vocabulary insert',
    'description' => t('%title (%name)', [
      '%title' => $vocabulary->get('name'),
      '%name' => $vocabulary->get('vid'),
    ]),
    'ref_char' => $vocabulary->get('vid'),
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_taxonomy_vocabulary_update().
 */
function admin_audit_trail_taxonomy_taxonomy_vocabulary_update($vocabulary) {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'vocabulary update',
    'description' => t('%title (%name)', [
      '%title' => $vocabulary->label(),
      '%name' => $vocabulary->getOriginalId(),
    ]),
    'ref_char' => $vocabulary->getOriginalId(),
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_taxonomy_vocabulary_delete().
 */
function admin_audit_trail_taxonomy_taxonomy_vocabulary_delete($vocabulary) {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'vocabulary delete',
    'description' => t('%title (%name)', [
      '%title' => $vocabulary->label(),
      '%name' => $vocabulary->getOriginalId(),
    ]),
    'ref_char' => $vocabulary->getOriginalId(),
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_taxonomy_term_insert().
 */
function admin_audit_trail_taxonomy_taxonomy_term_insert($term) {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'term insert',
    'description' => t('%name (%tid)', [
      '%name' => $term->getName(),
      '%tid' => $term->id(),
    ]),
    'ref_numeric' => $term->id(),
    'ref_char' => $term->get('vid')->target_id,
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_taxonomy_term_update().
 */
function admin_audit_trail_taxonomy_taxonomy_term_update($term) {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'term update',
    'description' => t('%name (%tid)', [
      '%name' => $term->getName(),
      '%tid' => $term->id(),
    ]),
    'ref_numeric' => $term->id(),
    'ref_char' => $term->get('vid')->target_id,
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_taxonomy_term_delete().
 */
function admin_audit_trail_taxonomy_taxonomy_term_delete($term) {
  $log = [
    'type' => 'taxonomy',
    'operation' => 'term delete',
    'description' => t('%name (%tid)', [
      '%name' => $term->getName(),
      '%tid' => $term->id(),
    ]),
    'ref_numeric' => $term->id(),
    'ref_char' => $term->get('vid')->target_id,
  ];
  admin_audit_trail_insert($log);
}
