<?php

/**
 * @file
 * Logs user authentication in the admin_audit_trail module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_admin_audit_trail_handlers().
 */
function admin_audit_trail_auth_admin_audit_trail_handlers() {
  // User Authentication event log handler.
  $handlers = [];
  $handlers['authentication'] = [
    'title' => t('User authentication'),
    'form_ids' => ['user_login_form', 'user_pass'],
    'form_submit_callback' => 'admin_audit_trail_auth_form_submit',
  ];
  return $handlers;
}

/**
 * Event log callback for the user authentication event log.
 *
 * @return array
 *   Return an associative array of data to insert in database.
 */
function admin_audit_trail_auth_form_submit($form, $form_state, $form_id) {
  $account = \Drupal::currentUser();
  $log = NULL;
  switch ($form_id) {
    case 'user_login_form':
      $log = [
        'operation' => 'login',
        'description' => t('%user (uid %uid)', [
          '%user' => $account->getDisplayName(),
          '%uid' => $account->id(),
        ]),
        'ref_numeric' => $account->id(),
        'ref_char' => $account->getDisplayName(),
      ];
      break;

    case 'user_pass':
      $uid = 0;
      $account = $form_state->getValue('account');
      if (isset($account)) {
        $uid = $account->id();
      }
      $log = [
        'operation' => 'request password',
        'description' => t('%user (uid %uid)', [
          '%user' => $form_state->getValue('name'),
          '%uid' => $uid,
        ]),
        'ref_numeric' => $uid,
        'ref_char' => $form_state->getValue('name'),
      ];
      break;
  }
  return $log;
}

/**
 * Implements hook_user_logout().
 */
function admin_audit_trail_auth_user_logout($account) {
  $log = [
    'type' => 'authentication',
    'operation' => 'logout',
    'description' => t('%user (uid %uid)', [
      '%user' => $account->getDisplayName(),
      '%uid' => $account->id(),
    ]),
    'ref_numeric' => $account->id(),
    'ref_char' => $account->getDisplayName(),
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function admin_audit_trail_auth_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#validate'][] = 'admin_audit_trail_auth_user_login_validate';
}

/**
 * Implements hook_form_FORM_ID_validate().
 */
function admin_audit_trail_auth_user_login_validate($form, &$form_state) {
  // Check for erros and log them.
  $errors = $form_state->getErrors();
  if (!empty($errors)) {
    $log = [
      'type' => 'authentication',
      'operation' => 'fail',
      'description' => t('%user', [
        '%user' => $form_state->getValue('name'),
      ]),
      'ref_char' => $form_state->getValue('name'),
    ];
    admin_audit_trail_insert($log);
  }
}
