<?php

/**
 * @file
 * Logs user CUD commands in the admin_audit_trail module.
 */

/**
 * Implements hook_admin_audit_trail_handlers().
 */
function admin_audit_trail_user_admin_audit_trail_handlers() {
  // User event log handler.
  $handlers = [];
  $handlers['user'] = [
    'title' => t('User'),
  ];
  return $handlers;
}

/**
 * Implements hook_user_insert().
 */
function admin_audit_trail_user_insert($account) {
  $log = [
    'type' => 'user',
    'operation' => 'insert',
    'description' => t('%name (uid %uid)', [
      '%name' => $account->getDisplayName(),
      '%uid' => $account->id(),
    ]),
    'ref_numeric' => $account->id(),
    'ref_char' => $account->getDisplayName(),
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_user_update().
 */
function admin_audit_trail_user_update($account) {
  $log = [
    'type' => 'user',
    'operation' => 'update',
    'description' => t('%name (uid %uid)', [
      '%name' => $account->original->getDisplayName(),
      '%uid' => $account->original->id(),
    ]),
    'ref_numeric' => $account->original->id(),
    'ref_char' => $account->getDisplayName(),
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_user_delete().
 */
function admin_audit_trail_user_delete($account) {
  $log = [
    'type' => 'user',
    'operation' => 'delete',
    'description' => t('%name (uid %uid)', [
      '%name' => $account->getDisplayName(),
      '%uid' => $account->id(),
    ]),
    'ref_numeric' => $account->id(),
    'ref_char' => $account->getDisplayName(),
  ];
  admin_audit_trail_insert($log);
}
